# Generated by Django 6.0.2 on 2026-02-25 10:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.FloatField(help_text='Hours used in current 8-day cycle')),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('pickup_lat', models.FloatField(blank=True, null=True)),
                ('pickup_lng', models.FloatField(blank=True, null=True)),
                ('dropoff_lat', models.FloatField(blank=True, null=True)),
                ('dropoff_lng', models.FloatField(blank=True, null=True)),
                ('total_distance_miles', models.FloatField(blank=True, null=True)),
                ('estimated_duration_hours', models.FloatField(blank=True, null=True)),
                ('route_polyline', models.JSONField(blank=True, help_text='GeoJSON LineString for the full route', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stop_type', models.CharField(choices=[('start', 'Start'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('fuel', 'Fuel Stop'), ('rest', '10-Hr Rest'), ('break', '30-Min Break')], max_length=20)),
                ('location_name', models.CharField(max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('duration_hours', models.FloatField(default=0.0)),
                ('cumulative_miles', models.FloatField(default=0.0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trip.trip')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('day_number', models.PositiveIntegerField()),
                ('activities', models.JSONField(default=list)),
                ('total_driving_hours', models.FloatField(default=0.0)),
                ('total_on_duty_hours', models.FloatField(default=0.0)),
                ('total_off_duty_hours', models.FloatField(default=0.0)),
                ('total_sleeper_hours', models.FloatField(default=0.0)),
                ('cycle_hours_used', models.FloatField(default=0.0, help_text='Cumulative cycle hours at end of day')),
                ('from_location', models.CharField(blank=True, max_length=255)),
                ('to_location', models.CharField(blank=True, max_length=255)),
                ('total_miles', models.FloatField(default=0.0)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='eld_logs/')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trip.trip')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('trip', 'day_number')},
            },
        ),
    ]
